apiVersion: 1
ingress:
  enabled: true
  hosts:
    - grafana.damdam.me
#adminUser: "admin"
adminPassword: "123456"
#datasources:
#  datasources.yaml:
#    apiVersion: 1
#    datasources:
#    - name: Prometheus
#      type: prometheus
#      url: http://prometheus-server
#      access: proxy
#      isDefault: true
#dashboards:
#  kubernetes-prometheus:
#    gnetId: 315
#    revision: 1
#    datasource: Prometheus
#  kubernetes-deployment:
#    gnetId: 741
#    revision: 1
#    datasource: Prometheus
#  kubernetes-nginx:
#    gnetId: 3050
#    revision: 1
#    datasource: Prometheus
#dashboardProviders:
#  dashboardproviders.yaml:
#    apiVersion: 1
#    providers:
#    - name: 'default'
#      type: file
#      editable: true
#      options:
#        path: ~/Opsschool/spree-project/kops/grafana
